CORES ?= $(shell nproc)
export CORES

BASEDIR := $(shell realpath ../..)

all:
	./bootstrap.sh --with-toolset=gcc
	./b2 install link=static variant=release threading=multi -a -q \
		--prefix=${BASEDIR}
